---
title: "Mini-Project 02"
output: 
  html_document:
    keep_md: true
    toc: true
    toc_float: true
---

# Data Visualization Project 02

_revised version of mini-project 02 goes here_

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
births <- read_csv("../data/us_births_00_14.csv")
library(plotly)
library(htmlwidgets)
```


```{r, message=FALSE}
library(sf)
fifa <- read_csv("../data/fifa18.csv")
head(fifa$nationality)
shape <- read_sf("../data/ne_10m_admin_0_countries.shp")

```

```{r, message=FALSE}
#rework 1
p <- births %>% ggplot( aes(x = date, y = births, color = year, text = paste(date))) + geom_point() +
  geom_smooth(
    aes(group = 1),
    method = "lm",
    formula = y ~ poly(x, 2),
    se = FALSE,
    color = "black"
  ) +
  scale_color_viridis_c() +
  labs(
    title = "Births Through the Years",
    x = "",
    y = "",
    caption = "Source: US Births 00 14"
  ) + theme(legend.position = "none") +
  annotate("text",
           x = 14000,
           y = 16500,
           label = "Birth Peak") + 
  annotate("text",
           x = 11500,
           y = 15500,
           label = "Low Left") + 
  annotate("text",
           x = 16000,
           y = 15500,
           label = "Low Right")

ggplotly(p, tooltip = "text")

```


```{r, message=FALSE}
#rework 2
p <- births %>% filter(births >= 10000) %>% ggplot( aes(x = date, y = births, color = year, text = paste(date))) + geom_point() +
  geom_smooth(
    aes(group = 1),
    method = "lm",
    formula = y ~ poly(x, 2),
    se = FALSE,
    color = "black"
  ) +
  scale_color_viridis_c() +
  labs(
    title = "Births Through the Years",
    x = "",
    y = "",
    caption = "Source: US Births 00 14"
  ) + theme(legend.position = "none") +
  annotate("text",
           x = 14000,
           y = 16500,
           label = "Birth Peak") + 
  annotate("text",
           x = 11500,
           y = 15500,
           label = "Low Left") + 
  annotate("text",
           x = 16000,
           y = 15500,
           label = "Low Right")

ggplotly(p, tooltip = "text")

```

```{r, message=FALSE}
#original
p <- ggplot(births, aes(x = date, y = births, color = year, text = paste(date))) + geom_point() +
  labs(
    title = "Births Through the Years",
    x = "",
    y = "",
    caption = "Source: US Births 00 14"
  ) + theme(legend.position = "none") +
  annotate("text",
           x = 14000,
           y = 16500,
           label = "Birth Peak") + 
  annotate("text",
           x = 11500,
           y = 15500,
           label = "Low Left") + 
  annotate("text",
           x = 16000,
           y = 15500,
           label = "Low Right")

ggplotly(p, tooltip = "text")

int_plot <- ggplotly(p, tooltip = "text")

saveWidget(int_plot, "int_plot.html", selfcontained = TRUE)
```

```{r, message=FALSE}
count <- fifa %>% count(nationality, name = "count")
map <- shape %>% left_join(count, by = c("NAME" = "nationality"))

p <- ggplot(map) + geom_sf(aes(fill = count, text = paste(NAME, ", Count: ", count))) + 
  scale_fill_viridis_c() +
  labs(
    title = "Fifa 18 Player Nationality World Map",
    x = "",
    y = "",
    caption = "Source: fifa18 dataset"
  )

ggplotly(p, tooltip = "text")
```

```{r, message=FALSE}
year_births <- births %>% group_by(year) %>% summarise(avg_births = mean(births))

model <- lm(avg_births ~ year, data = year_births)

ggplot(year_births, aes(x = year, y = avg_births)) + geom_point() +
  geom_smooth(method = "lm") +
  labs(
    title = "Model of Births by Year",
    x = "",
    y = "",
    caption = "Source: US Births 00 14"
  )
```

